/* eslint-disable @typescript-eslint/naming-convention */

/**
 * Validation Rules:
 * - lvl: Must be a number between 1 and 10
 * - hp/sp: Can be a number (e.g., "28"), percentage (e.g., "10%"), or comparison expression (e.g., "< 10%", ">= 50")
 */

export interface ConfigKeyInfo {
    default: string;
    description: string;
}

export const configKeys: Record<string, any> = {
    master: "",
    server: "",
    username: "",
    password: "",
    loginPinCode: "",
    char: "",
    otpSeed: "",
    poseidonServer: "127.0.0.1",
    poseidonPort: "24390",
    poseidonTimeout: "5",
    bindIp: "",
    forceMapIP: "",
    XKore: "0",
    XKore_port: "2350",
    XKore_dll: "NetRedirect.dll",
    XKore_injectDLL: "1",
    XKore_autoAttachIfOneExe: "1",
    XKore_silent: "1",
    XKore_bypassBotDetection: "0",
    XKore_exeName: "ragexe.exe",
    XKore_listenIp: "127.0.0.1",
    XKore_listenPort: "6901",
    XKore_publicIp: "127.0.0.1",
    XKore_ID: "",
    secureAdminPassword: "1",
    adminPassword: "",
    callSign: "",
    commandPrefix: ";",
    callSignGM: "0",
    inGameAuth: "0",
    macAddress: "",
    pauseCharLogin: "2",
    pauseCharServer: "0",
    pauseMapServer: "0",
    ignoreInvalidLogin: "0",
    whenInGame_requestCashPoints: "0",
    message_length_max: "80",
    alias_heal: "sp 28",
    allowedMaps: "",
    allowedMaps_reaction: "1",
    attackAuto: "2",
    attackAuto_party: "1",
    attackAuto_onlyWhenSafe: "0",
    attackAuto_followTarget: "1",
    attackAuto_inLockOnly: "1",
    attackAuto_notInTown: "1",
    attackAuto_notWhile_storageAuto: "1",
    attackAuto_notWhile_buyAuto: "1",
    attackAuto_notWhile_sellAuto: "1",
    attackAuto_considerDamagedAggressive: "0",
    attackDistance: "1",
    attackDistanceAuto: "1",
    attackMaxDistance: "1",
    attackMaxRouteTime: "4",
    attackMinPlayerDistance: "2",
    attackMinPortalDistance: "4",
    attackUseWeapon: "1",
    attackNoGiveup: "0",
    attackCanSnipe: "0",
    attackCheckLOS: "1",
    attackRouteMaxPathDistance: "20",
    attackLooters: "0",
    attackLooters_dist: "1",
    attackChangeTarget: "1",
    aggressiveAntiKS: "0",
    attackUpdateMonsterPos: "1",
    attackBeyondMaxDistance_waitForAgressive: "0",
    attackBeyondMaxDistance_sendAttackWhileWaiting: "0",
    attackSendAttackWithMove: "0",
    attackWaitApproachFinish: "1",
    autoMoveOnDeath: "0",
    autoMoveOnDeath_x: "",
    autoMoveOnDeath_y: "",
    autoMoveOnDeath_map: "",
    attackEquip_topHead: "",
    attackEquip_midHead: "",
    attackEquip_lowHead: "",
    attackEquip_leftHand: "",
    attackEquip_rightHand: "",
    attackEquip_leftAccessory: "",
    attackEquip_rightAccessory: "",
    attackEquip_robe: "",
    attackEquip_armor: "",
    attackEquip_shoes: "",
    attackEquip_arrow: "",
    autoBreakTime: {
        startTime: "",
        stopTime: "",
    },
    autoConfChange: {
        minTime: "",
        varTime: "",
        lvl: "",
        joblvl: "",
    },
    autoMakeArrows: "0",
    autoRestart: "0",
    autoRestartMin: "10800",
    autoRestartSeed: "3600",
    autoRestartSleep: "1",
    autoSleepMin: "900",
    autoSleepSeed: "900",
    autoResponse: "0",
    autoResponseOnHeal: "0",
    autoSpell: "",
    autoSpell_safe: "",
    autoPoison: "",
    avoidGM_namePattern: "",
    avoidGM_near: "0",
    avoidGM_near_inTown: "0",
    avoidGM_talk: "0",
    avoidGM_reconnect: "1800",
    avoidGM_ignoreList: "",
    avoidList: "1",
    avoidList_inLockOnly: "0",
    avoidList_reconnect: "1800",
    avoidList_ignoreList: "",
    avoidHiddenActors: "0",
    avoidHiddenMonsters: "0",
    cachePlayerNames: "1",
    cachePlayerNames_duration: "900",
    cachePlayerNames_maxSize: "100",
    clientSight: "17",
    dcPause: "1",
    dcOnDeath: "0",
    dcOnDualLogin: "0",
    dcOnDisconnect: "0",
    dcOnEmptyArrow: "0",
    dcOnMaxReconnections: "0",
    dcOnMute: "0",
    dcOnPM: "0",
    dcOnZeny: "0",
    dcOnStorageFull: "1",
    dcOnPlayer: "0",
    dcOnServerShutDown: "0",
    dcOnServerClose: "0",
    dcOnJobLevel: "",
    dcOnLevel: "",
    follow: "0",
    followTarget: "",
    followEmotion: "1",
    followEmotion_distance: "4",
    followFaceDirection: "0",
    followDistanceMax: "6",
    followDistanceMin: "3",
    followLostStep: "12",
    followSitAuto: "0",
    followBot: "0",
    itemsTakeAuto: "2",
    itemsTakeAuto_party: "0",
    itemsGatherAuto: "2",
    itemsGatherAuto_notInTown: "0",
    itemsGatherAutoMinPlayerDistance: "6",
    itemsGatherAutoMinPortalDistance: "5",
    itemsMaxWeight: "89",
    itemsMaxWeight_sellOrStore: "48",
    itemsMaxNum_sellOrStore: "99",
    cartMaxWeight: "7900",
    itemsTakeGreed: "0",
    itemsCheckWeight: "1",
    lockMap: "",
    lockMap_x: "",
    lockMap_y: "",
    lockMap_randX: "",
    lockMap_randY: "",
    route_escape_reachedNoPortal: "1",
    route_escape_randomWalk: "1",
    route_escape_shout: "",
    route_avoidWalls: "1",
    route_randomWalk: "1",
    route_randomWalk_inTown: "0",
    route_randomWalk_maxRouteTime: "75",
    route_maxWarpFee: "",
    route_maxNpcTries: "5",
    route_teleport: "0",
    route_teleport_minDistance: "75",
    route_teleport_maxTries: "8",
    route_teleport_notInMaps: "",
    route_step: "10",
    route_removeMissingPortals_NPC: "1",
    route_removeMissingPortals: "0",
    route_tryToGuessMissingPortalByDistance: "1",
    route_reAddMissingPortals: "1",
    route_randomFactor: "0",
    maxWalkPathDistance: "17",
    runFromTarget: "0",
    runFromTarget_inAdvance: "0",
    runFromTarget_dist: "5",
    runFromTarget_minStep: "7",
    runFromTarget_maxPathDistance: "13",
    runFromTarget_noAttackMethodFallback: "0",
    runFromTarget_noAttackMethodFallback_attackMaxDist: "14",
    runFromTarget_noAttackMethodFallback_minStep: "8",
    saveMap: "",
    saveMap_x: "",
    saveMap_y: "",
    saveMap_warpToBuyOrSell: "1",
    saveMap_warpChatCommand: "",
    memo1: "",
    memo2: "",
    memo3: "",
    memo4: "",
    shopAuto_open: "0",
    shop_random: "0",
    shop_useSkill: "1",
    buyerShopAuto_open: "0",
    buyerShop_random: "0",
    sitAuto_hp_lower: "40",
    sitAuto_hp_upper: "100",
    sitAuto_sp_lower: "0",
    sitAuto_sp_upper: "0",
    sitAuto_follow: "0",
    sitAuto_over_50: "0",
    sitAuto_idle: "1",
    sitAuto_look: "",
    sitAuto_look_from_wall: "",
    sitTensionRelax: "0",
    statsAddAuto: "0",
    statsAddAuto_list: "",
    statsAddAuto_dontUseBonus: "0",
    statsAdd_over_99: "1",
    skillsAddAuto: "0",
    skillsAddAuto_list: "",
    tankMode: "0",
    tankModeTarget: "",
    teleportAuto_hp: "10",
    teleportAuto_sp: "0",
    teleportAuto_idle: "0",
    teleportAuto_portal: "0",
    teleportAuto_search: "0",
    teleportAuto_minAggressives: "0",
    teleportAuto_minAggressivesInLock: "0",
    teleportAuto_onlyWhenSafe: "0",
    teleportAuto_maxDmg: "500",
    teleportAuto_maxDmgInLock: "0",
    teleportAuto_deadly: "1",
    teleportAuto_useSkill: "1",
    teleportAuto_useChatCommand: "",
    teleportAuto_allPlayers: "0",
    teleportAuto_notPlayers: "",
    teleportAuto_atkCount: "0",
    teleportAuto_atkMiss: "10",
    teleportAuto_unstuck: "0",
    teleportAuto_lostTarget: "0",
    teleportAuto_dropTarget: "0",
    teleportAuto_dropTargetKS: "0",
    teleportAuto_dropTargetHidden: "0",
    teleportAuto_attackedWhenSitting: "0",
    teleportAuto_totalDmg: "0",
    teleportAuto_totalDmgInLock: "0",
    teleportAuto_equip_leftAccessory: "",
    teleportAuto_equip_rightAccessory: "",
    teleportAuto_lostHomunculus: "",
    teleportAuto_useItemForRespawn: "",
    teleportAuto_item1: "",
    teleportAuto_item2: "",
    dealAuto: "1",
    dealAuto_names: "",
    partyAuto: "1",
    partyAutoShare: "0",
    partyAutoShareItem: "0",
    partyAutoShareItemDiv: "0",
    guildAutoDeny: "1",
    attendanceAuto: "1",
    verbose: "1",
    showDomain: "0",
    showDomain_NPC: "parseMsg_presence",
    showDomain_Shop: "list",
    squelchDomains: "",
    verboseDomains: "",
    beepDomains: "",
    beepDomains_notInTown: "",
    friendlyAID: "",
    showTime: "",
    showTimeDomains: "",
    showTimeDomainsFormat: "",
    wx_map_maxAutoSize: "300",
    wx_map_monsterSticking: "1",
    wx_map_npcSticking: "1",
    wx_map_playersSticking: "1",
    wx_map_portalSticking: "5",
    wx_map_route: "",
    wx_npcTalk: "",
    wx_captcha: "",
    showAllDamage: "0",
    manualURL: "https://openkore.com/wiki/Manual",
    forumURL: "https://forums.openkore.com",
    logChat: "1",
    logPrivateChat: "1",
    logPartyChat: "1",
    logGuildChat: "1",
    logSystemChat: "1",
    logLocalBroadcast: "1",
    logShop: "1",
    logEmoticons: "",
    logConsole: "1",
    logAppendUsername: "1",
    logAppendServer: "0",
    monsterLog: "0",
    playerLog: "0",
    logDead: "1",
    questDisplayStyle: "2",
    chatTitleOversize: "0",
    shopTitleOversize: "0",
    buyerShopTitleOversize: "0",
    sleepTime: "10000",
    ignoreAll: "0",
    itemHistory: "0",
    autoTalkCont: "1",
    noAutoSkill: "0",
    portalCompile: "1",
    portalRecord: "2",
    portalRecord_recompileAfter: "1",
    missDamage: "0",
    tankersList: "",
    repairAuto: "0",
    repairAuto_list: "",
    status_mapProperty: "0",
    status_mapType: "0",
    monster_filter: "",
    mercenary_attackAuto: "2",
    mercenary_attackAuto_party: "1",
    mercenary_attackAuto_notInTown: "1",
    mercenary_attackAuto_inLockOnly: "1",
    mercenary_attackAuto_notWhile_storageAuto: "1",
    mercenary_attackAuto_notWhile_buyAuto: "1",
    mercenary_attackAuto_notWhile_sellAuto: "1",
    mercenary_attackAuto_considerDamagedAggressive: "0",
    mercenary_attackAuto_onlyWhenSafe: "0",
    mercenary_attackAuto_duringRandomWalk: "0",
    mercenary_attackAuto_duringItemsTake: "0",
    mercenary_attackDistance: "1",
    mercenary_attackMaxDistance: "1",
    mercenary_attackDistanceAuto: "1",
    mercenary_attackMaxRouteTime: "4",
    mercenary_attackCanSnipe: "0",
    mercenary_attackCheckLOS: "1",
    mercenary_attackRouteMaxPathDistance: "20",
    mercenary_attackUseWeapon: "1",
    mercenary_attackNoGiveup: "0",
    mercenary_attackChangeTarget: "1",
    mercenary_attack_dance_melee: "0",
    mercenary_attack_dance_ranged: "0",
    mercenary_attackBeyondMaxDistance_waitForAgressive: "0",
    mercenary_attackBeyondMaxDistance_sendAttackWhileWaiting: "0",
    mercenary_attackSendAttackWithMove: "0",
    mercenary_attackWaitApproachFinish: "1",
    mercenary_lost_teleportToMaster_maxTries: "6",
    mercenary_route_randomWalk_rescueWhenLost: "0",
    mercenary_route_randomWalk_stopDuringAttack: "0",
    mercenary_route_randomWalk_waitMinDistance: "0",
    mercenary_runFromTarget: "0",
    mercenary_runFromTarget_inAdvance: "0",
    mercenary_runFromTarget_dist: "5",
    mercenary_runFromTarget_minStep: "7",
    mercenary_runFromTarget_maxPathDistance: "20",
    mercenary_runFromTarget_noAttackMethodFallback: "0",
    mercenary_runFromTarget_noAttackMethodFallback_attackMaxDist: "14",
    mercenary_runFromTarget_noAttackMethodFallback_minStep: "8",
    mercenary_idleWalkType: "1",
    mercenary_followDistanceMin: "3",
    mercenary_followDistanceMax: "12",
    mercenary_moveNearWhenIdle: "1",
    mercenary_moveNearWhenIdle_minDistance: "3",
    mercenary_moveNearWhenIdle_maxDistance: "8",
    mercenary_route_step: "10",
    mercenary_tankMode: "0",
    mercenary_tankModeTarget: "",
    mercenary_teleportAuto_hp: "10",
    mercenary_teleportAuto_maxDmg: "500",
    mercenary_teleportAuto_maxDmgInLock: "0",
    mercenary_teleportAuto_deadly: "1",
    mercenary_teleportAuto_unstuck: "0",
    mercenary_teleportAuto_dropTarget: "0",
    mercenary_teleportAuto_dropTargetKS: "0",
    mercenary_teleportAuto_totalDmg: "0",
    mercenary_teleportAuto_totalDmgInLock: "0",
    mercenary_teleportAuto_attackedWhenSitting: "0",
    homunculus_attackAuto: "2",
    homunculus_attackAuto_party: "1",
    homunculus_attackAuto_notInTown: "1",
    homunculus_attackAuto_inLockOnly: "1",
    homunculus_attackAuto_notWhile_storageAuto: "1",
    homunculus_attackAuto_notWhile_buyAuto: "1",
    homunculus_attackAuto_notWhile_sellAuto: "1",
    homunculus_attackAuto_considerDamagedAggressive: "0",
    homunculus_attackAuto_onlyWhenSafe: "0",
    homunculus_attackAuto_duringRandomWalk: "0",
    homunculus_attackAuto_duringItemsTake: "0",
    homunculus_attackDistance: "1",
    homunculus_attackMaxDistance: "1",
    homunculus_attackDistanceAuto: "1",
    homunculus_attackMaxRouteTime: "4",
    homunculus_attackCanSnipe: "0",
    homunculus_attackCheckLOS: "1",
    homunculus_attackRouteMaxPathDistance: "20",
    homunculus_attackUseWeapon: "1",
    homunculus_attackNoGiveup: "0",
    homunculus_attackChangeTarget: "1",
    homunculus_attack_dance_melee: "0",
    homunculus_attackBeyondMaxDistance_waitForAgressive: "0",
    homunculus_attackBeyondMaxDistance_sendAttackWhileWaiting: "0",
    homunculus_attackSendAttackWithMove: "0",
    homunculus_attackWaitApproachFinish: "1",
    homunculus_lost_teleportToMaster_maxTries: "6",
    homunculus_route_randomWalk_rescueWhenLost: "0",
    homunculus_route_randomWalk_stopDuringAttack: "0",
    homunculus_route_randomWalk_waitMinDistance: "0",
    homunculus_runFromTarget: "0",
    homunculus_runFromTarget_dist: "5",
    homunculus_runFromTarget_minStep: "7",
    homunculus_runFromTarget_maxPathDistance: "20",
    homunculus_runFromTarget_noAttackMethodFallback: "0",
    homunculus_runFromTarget_noAttackMethodFallback_attackMaxDist: "14",
    homunculus_runFromTarget_noAttackMethodFallback_minStep: "8",
    homunculus_idleWalkType: "1",
    homunculus_followDistanceMin: "3",
    homunculus_followDistanceMax: "12",
    homunculus_moveNearWhenIdle: "1",
    homunculus_moveNearWhenIdle_minDistance: "3",
    homunculus_moveNearWhenIdle_maxDistance: "8",
    homunculus_route_step: "10",
    homunculus_tankMode: "0",
    homunculus_tankModeTarget: "",
    homunculus_StandByAuto: "0",
    homunculus_teleportAuto_hp: "10",
    homunculus_teleportAuto_maxDmg: "500",
    homunculus_teleportAuto_maxDmgInLock: "0",
    homunculus_teleportAuto_deadly: "1",
    homunculus_teleportAuto_unstuck: "0",
    homunculus_teleportAuto_dropTarget: "0",
    homunculus_teleportAuto_dropTargetKS: "0",
    homunculus_teleportAuto_totalDmg: "0",
    homunculus_teleportAuto_totalDmgInLock: "0",
    homunculus_teleportAuto_attackedWhenSitting: "0",
    homunculus_autoFeed: "1",
    homunculus_hunger: "15",
    homunculus_return: "11",
    homunculus_autoFeedAllowedMaps: "",
    pet_autoFeed: "1",
    pet_hunger: "25",
    pet_return: "20",
    attackSkillSlot: {
        lvl: "",
        dist: "1",
        maxDist: "1",
        maxCastTime: "0",
        minCastTime: "0",
        hp: "",
        sp: "> 10",
        ap: "",
        homunculus: "",
        homunculus_hp: "",
        homunculus_sp: "",
        homunculus_dead: "",
        homunculus_resting: "",
        homunculus_noinfo_dead: "",
        homunculus_noinfo_resting: "",
        homunculus_onAction: "",
        homunculus_notOnAction: "",
        homunculus_whenIdle: "",
        homunculus_whenNotIdle: "",
        mercenary: "",
        mercenary_hp: "",
        mercenary_sp: "",
        mercenary_whenStatusActive: "",
        mercenary_whenStatusInactive: "",
        mercenary_onAction: "",
        mercenary_notOnAction: "",
        mercenary_whenIdle: "",
        mercenary_whenNotIdle: "",
        onAction: "",
        inQueue: "",
        notInQueue: "",
        whenStatusActive: "",
        whenStatusInactive: "",
        whenFollowing: "",
        spirit: "",
        amuletType: "",
        aggressives: "",
        previousDamage: "",
        stopWhenHit: "0",
        inLockOnly: "0",
        notInTown: "0",
        timeout: "0",
        disabled: "0",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        maxAttempts: "0",
        maxUses: "0",
        target_hp: "",
        target_whenStatusActive: "",
        target_whenStatusInactive: "",
        target_deltaHp: "",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
        inInventory: "",
        isSelfSkill: "0",
        isStartSkill: "0",
        equip_topHead: "",
        equip_midHead: "",
        equip_lowHead: "",
        equip_leftHand: "",
        equip_rightHand: "",
        equip_leftAccessory: "",
        equip_rightAccessory: "",
        equip_robe: "",
        equip_armor: "",
        equip_shoes: "",
        equip_arrow: "",
        manualAI: "0",
    },
    attackComboSlot: {
        afterSkill: "",
        waitBeforeUse: "",
        dist: "1",
        maxDist: "1",
        isSelfSkill: "1",
        target_hp: "",
        target_deltaHp: "",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
    },
    doCommand: {
        hp: "",
        sp: "",
        ap: "",
        homunculus: "",
        homunculus_hp: "",
        homunculus_sp: "",
        homunculus_dead: "",
        homunculus_resting: "",
        homunculus_noinfo_dead: "",
        homunculus_noinfo_resting: "",
        homunculus_onAction: "",
        homunculus_notOnAction: "",
        homunculus_whenIdle: "",
        homunculus_whenNotIdle: "",
        mercenary: "",
        mercenary_hp: "",
        mercenary_sp: "",
        mercenary_whenStatusActive: "",
        mercenary_whenStatusInactive: "",
        mercenary_onAction: "",
        mercenary_notOnAction: "",
        mercenary_whenIdle: "",
        mercenary_whenNotIdle: "",
        onAction: "",
        inQueue: "",
        notInQueue: "",
        whenStatusActive: "",
        whenStatusInactive: "",
        whenFollowing: "",
        spirit: "",
        amuletType: "",
        aggressives: "",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        stopWhenHit: "0",
        inLockOnly: "0",
        notWhileSitting: "0",
        notInTown: "0",
        timeout: "",
        disabled: "0",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
        inInventory: "",
        inCart: "",
        inMap: "",
        manualAI: "0",
    },
    useSelf_skill: {
        lvl: "",
        maxCastTime: "0",
        minCastTime: "0",
        hp: "",
        sp: "",
        ap: "",
        homunculus: "",
        homunculus_hp: "",
        homunculus_sp: "",
        homunculus_dead: "",
        homunculus_resting: "",
        homunculus_noinfo_dead: "",
        homunculus_noinfo_resting: "",
        homunculus_onAction: "",
        homunculus_notOnAction: "",
        homunculus_whenIdle: "",
        homunculus_whenNotIdle: "",
        mercenary: "",
        mercenary_hp: "",
        mercenary_sp: "",
        mercenary_whenStatusActive: "",
        mercenary_whenStatusInactive: "",
        mercenary_onAction: "",
        mercenary_notOnAction: "",
        mercenary_whenIdle: "",
        mercenary_whenNotIdle: "",
        onAction: "",
        inQueue: "",
        notInQueue: "",
        whenStatusActive: "",
        whenStatusInactive: "",
        whenFollowing: "",
        spirit: "",
        amuletType: "",
        aggressives: "",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        stopWhenHit: "0",
        inLockOnly: "0",
        notWhileSitting: "0",
        notInTown: "0",
        timeout: "0",
        disabled: "0",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
        inInventory: "",
        manualAI: "0",
    },
    useSelf_skill_smartHeal: "1",
    partySkillDistance: "0..8",
    partySkill: {
        lvl: "",
        dist: "1",
        maxDist: "8",
        maxCastTime: "0",
        minCastTime: "0",
        hp: "",
        sp: "",
        ap: "",
        homunculus: "",
        homunculus_hp: "",
        homunculus_sp: "",
        homunculus_dead: "",
        homunculus_resting: "",
        homunculus_noinfo_dead: "",
        homunculus_noinfo_resting: "",
        homunculus_onAction: "",
        homunculus_notOnAction: "",
        homunculus_whenIdle: "",
        homunculus_whenNotIdle: "",
        mercenary: "",
        mercenary_hp: "",
        mercenary_sp: "",
        mercenary_whenStatusActive: "",
        mercenary_whenStatusInactive: "",
        mercenary_onAction: "",
        mercenary_notOnAction: "",
        mercenary_whenIdle: "",
        mercenary_whenNotIdle: "",
        onAction: "",
        inQueue: "",
        notInQueue: "",
        whenStatusActive: "",
        whenStatusInactive: "",
        whenFollowing: "",
        spirit: "",
        amuletType: "",
        aggressives: "",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        stopWhenHit: "0",
        inLockOnly: "0",
        notWhileSitting: "0",
        notInTown: "0",
        timeout: "0",
        disabled: "0",
        manualAI: "0",
        target: "",
        target_hp: "",
        target_isJob: "",
        target_isNotJob: "",
        target_whenStatusActive: "",
        target_whenStatusInactive: "",
        target_aggressives: "",
        target_monsters: "",
        target_timeout: "0",
        target_deltaHp: "",
        target_dead: "0",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
        inInventory: "",
        isSelfSkill: "0",
    },
    monsterSkill: {
        target: "",
        maxUses: "",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
    },
    autoSwitch_default_rightHand: "",
    autoSwitch_default_leftHand: "",
    autoSwitch_default_arrow: "",
    autoSwitch: {
        rightHand: "",
        leftHand: "",
        arrow: "",
        distance: "",
        useWeapon: "",
    },
    equipAuto: {
        topHead: "",
        midHead: "",
        lowHead: "",
        leftHand: "",
        rightHand: "",
        leftAccessory: "",
        rightAccessory: "",
        robe: "",
        armor: "",
        shoes: "",
        arrow: "",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        weight: "0",
        whileSitting: "0",
        hp: "",
        sp: "",
        ap: "",
        homunculus: "",
        homunculus_hp: "",
        homunculus_sp: "",
        homunculus_dead: "",
        homunculus_resting: "",
        homunculus_noinfo_dead: "",
        homunculus_noinfo_resting: "",
        homunculus_onAction: "",
        homunculus_notOnAction: "",
        homunculus_whenIdle: "",
        homunculus_whenNotIdle: "",
        mercenary: "",
        mercenary_hp: "",
        mercenary_sp: "",
        mercenary_whenStatusActive: "",
        mercenary_whenStatusInactive: "",
        mercenary_onAction: "",
        mercenary_notOnAction: "",
        mercenary_whenIdle: "",
        mercenary_whenNotIdle: "",
        onAction: "",
        inQueue: "",
        notInQueue: "",
        whenStatusActive: "",
        whenStatusInactive: "",
        whenFollowing: "",
        spirit: "",
        amuletType: "",
        aggressives: "",
        stopWhenHit: "0",
        inLockOnly: "0",
        notWhileSitting: "0",
        notInTown: "0",
        timeout: "0",
        disabled: "0",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
        inInventory: "",
        manualAI: "0",
    },
    useSelf_item: {
        hp: "",
        sp: "",
        ap: "",
        homunculus: "",
        homunculus_hp: "",
        homunculus_sp: "",
        homunculus_dead: "",
        homunculus_resting: "",
        homunculus_noinfo_dead: "",
        homunculus_noinfo_resting: "",
        homunculus_onAction: "",
        homunculus_notOnAction: "",
        homunculus_whenIdle: "",
        homunculus_whenNotIdle: "",
        mercenary: "",
        mercenary_hp: "",
        mercenary_sp: "",
        mercenary_whenStatusActive: "",
        mercenary_whenStatusInactive: "",
        mercenary_onAction: "",
        mercenary_notOnAction: "",
        mercenary_whenIdle: "",
        mercenary_whenNotIdle: "",
        onAction: "",
        inQueue: "",
        notInQueue: "",
        whenStatusActive: "",
        whenStatusInactive: "",
        whenFollowing: "",
        spirit: "",
        amuletType: "",
        aggressives: "",
        monsters: "",
        notMonsters: "",
        monstersCount: "",
        monstersCountDist: "",
        stopWhenHit: "0",
        inLockOnly: "0",
        notWhileSitting: "0",
        notInTown: "0",
        timeout: "0",
        disabled: "0",
        whenPartyMembersNear: "",
        whenPartyMembersNearDist: "",
        inInventory: "",
        manualAI: "0",
    },
    buyAuto: {
        npc: "",
        npc_steps: "b",
        isMarket: "0",
        standpoint: "",
        distance: "3",
        price: "",
        minAmount: "2",
        maxAmount: "3",
        batchSize: "",
        onlyIdentified: "",
        disabled: "0",
        maxBase: "",
        minBase: "",
    },
    sellAuto: "0",
    sellAuto_npc: "",
    sellAuto_standpoint: "",
    sellAuto_distance: "3",
    sellAuto_maxDistance: "",
    sellAuto_npc_steps: "s",
    storageAuto: "0",
    storageAuto_onStart: "0",
    storageAuto_npc: "",
    storageAuto_standpoint: "",
    storageAuto_distance: "3",
    storageAuto_maxDistance: "",
    storageAuto_npc_type: "1",
    storageAuto_type: "0",
    storageAuto_npc_steps: "",
    storageAuto_password: "",
    storageAuto_keepOpen: "0",
    storageAuto_useChatCommand: "",
    storageAuto_useItem: "0",
    storageAuto_useItem_item: "",
    storageAuto_notAfterDeath: "",
    relogAfterStorage: "0",
    minStorageZeny: "50",
    npcTimeResponse: "",
    npcWrongStepsMethod: "0",
    getAuto: {
        minAmount: "",
        maxAmount: "",
        batchSize: "",
        passive: "",
        disabled: "0",
    },
    debug: "0",
    debugPacket_unparsed: "0",
    debugPacket_received: "0",
    debugPacket_ro_sent: "0",
    debugPacket_sent: "0",
    debugPacket_exclude: "",
    debugPacket_include: "",
    debugPacket_include_dumpMethod: "",
    debugDomains: "",
    logToFile_Debug: "",
    logToFile_Errors: "",
    logToFile_Messages: "",
    logToFile_Warnings: "",
    history_max: "50",
};

export const configDescriptions: Record<string, string> = {
    // Login & Connection
    master: "Master server hostname or IP address",
    server: "RO server name (used with master)",
    username: "Account username for login",
    password: "Account password for login",
    loginPinCode: "PIN code for account protection (if set)",
    char: "Character name to select on login",
    otpSeed: "One-Time Password seed for 2FA authentication",
    poseidonServer: "Poseidon query server address",
    poseidonPort: "Poseidon query server port",
    poseidonTimeout: "Poseidon query timeout in seconds",
    bindIp: "Local IP address to bind to",
    forceMapIP: "Force a specific map server IP",

    // XKore
    XKore: "XKore mode: 0=disabled, 1=hook into client, 2=proxy mode",
    XKore_port: "Port for XKore proxy to listen on",
    XKore_dll: "DLL file for XKore injection",
    XKore_injectDLL: "Whether to inject DLL for XKore: 0=no, 1=yes",
    XKore_autoAttachIfOneExe:
        "Auto-attach if only one RO process found: 0=no, 1=yes",
    XKore_silent: "Run XKore silently: 0=no, 1=yes",
    XKore_bypassBotDetection: "Attempt to bypass bot detection: 0=no, 1=yes",
    XKore_exeName: "RO executable name to target",
    XKore_listenIp: "IP to listen on for XKore proxy",
    XKore_listenPort: "Port to listen on for XKore proxy",
    XKore_publicIp: "Public IP to report for XKore proxy",

    // Administration
    secureAdminPassword: "Enable secure admin password protection: 0=no, 1=yes",
    adminPassword: "Admin password for bot control",
    callSign: "Call sign for addressing the bot",
    commandPrefix: "Prefix for bot commands",
    callSignGM: "Treat GM as call sign: 0=no, 1=yes",
    inGameAuth: "Require in-game authentication: 0=no, 1=yes",
    macAddress: "MAC address for multi-boxing",

    // Character Management
    pauseCharLogin: "Pause between character logins (seconds)",
    pauseCharServer: "Pause on character server (seconds)",
    pauseMapServer: "Pause on map server (seconds)",
    ignoreInvalidLogin: "Ignore invalid login errors: 0=no, 1=yes",
    whenInGame_requestCashPoints:
        "Request cash points when in-game: 0=no, 1=yes",
    message_length_max: "Maximum message length",

    // Attack Settings
    attackAuto: "Automatic attack mode: 0=off, 1=attack, 2=attack+skill",
    attackAuto_party: "Attack monsters hitting party members: 0=no, 1=yes",
    attackAuto_onlyWhenSafe:
        "Only attack when no aggressive monsters nearby: 0=no, 1=yes",
    attackAuto_followTarget: "Follow the target while attacking: 0=no, 1=yes",
    attackAuto_inLockOnly: "Only attack when in lockMap: 0=no, 1=yes",
    attackAuto_notInTown: "Don't attack in towns/cities: 0=no, 1=yes",
    attackAuto_notWhile_storageAuto:
        "Don't attack while managing storage: 0=no, 1=yes",
    attackAuto_notWhile_buyAuto: "Don't attack while buying: 0=no, 1=yes",
    attackAuto_notWhile_sellAuto: "Don't attack while selling: 0=no, 1=yes",
    attackAuto_considerDamagedAggressive:
        "Consider damaged players as aggressive: 0=no, 1=yes",
    attackDistance: "Preferred attack distance",
    attackDistanceAuto: "Automatically adjust attack distance: 0=no, 1=yes",
    attackMaxDistance: "Maximum attack distance",
    attackMaxRouteTime: "Max time to route to target (seconds)",
    attackMinPlayerDistance: "Minimum distance from other players",
    attackMinPortalDistance: "Minimum distance from portals",
    attackUseWeapon: "Use weapon when attacking: 0=no, 1=yes",
    attackNoGiveup: "Never give up attacking: 0=no, 1=yes",
    attackCanSnipe: "Allow snipe attacks: 0=no, 1=yes",
    attackCheckLOS: "Check line of sight before attacking: 0=no, 1=yes",
    attackRouteMaxPathDistance: "Max path distance for attack route",
    attackLooters: "Attack players who loot your kills: 0=no, 1=yes",
    attackLooters_dist: "Distance to check for looters",
    attackChangeTarget: "Change target if attacked: 0=no, 1=yes",
    aggressiveAntiKS: "Aggressive anti-KS behavior: 0=no, 1=yes",
    attackUpdateMonsterPos:
        "Update monster position during attack: 0=no, 1=yes",

    // Auto Behaviors
    autoMoveOnDeath:
        "Automatically move to specified location after death: 0=no, 1=yes",
    autoMoveOnDeath_x: "X coordinate for auto-move on death",
    autoMoveOnDeath_y: "Y coordinate for auto-move on death",
    autoMoveOnDeath_map: "Map for auto-move on death",
    autoBreakTime: "Schedule automatic breaks: 0=no, 1=yes",
    autoConfChange: "Change configuration based on level: 0=no, 1=yes",
    autoMakeArrows: "Automatically create arrows: 0=no, 1=yes",
    autoRestart: "Automatically restart after disconnect: 0=no, 1=yes",
    autoRestartMin: "Minimum time before auto-restart (seconds)",
    autoRestartSeed: "Random variation for auto-restart (seconds)",
    autoRestartSleep: "Sleep before auto-restart: 0=no, 1=yes",
    autoSleepMin: "Minimum sleep time (seconds)",
    autoSleepSeed: "Random sleep variation (seconds)",
    autoResponse: "Automatically respond to messages: 0=no, 1=yes",
    autoResponseOnHeal: "Respond when healed: 0=no, 1=yes",
    autoSpell: "Auto-cast spell (when idle): 0=no, 1=yes",
    autoSpell_safe: "Auto-cast spell only when safe: 0=no, 1=yes",
    autoPoison: "Auto-poison weapon: 0=no, 1=yes",

    // Avoidance Settings
    avoidGM_namePattern: "Pattern to identify GMs to avoid",
    avoidGM_near: "Avoid when GM is nearby: 0=no, 1=yes",
    avoidGM_near_inTown: "Avoid GMs in towns too: 0=no, 1=yes",
    avoidGM_talk: "Don't talk to GMs: 0=no, 1=yes",
    avoidGM_reconnect: "Time before reconnecting after GM spotted (seconds)",
    avoidGM_ignoreList: "List of GMs to ignore",
    avoidList: "Enable player avoidance list: 0=no, 1=yes",
    avoidList_inLockOnly: "Only avoid when locked to map: 0=no, 1=yes",
    avoidList_reconnect: "Reconnect time when avoided player found (seconds)",
    avoidList_ignoreList: "Ignore list for avoidance",
    avoidHiddenActors: "Avoid hidden players: 0=no, 1=yes",
    avoidHiddenMonsters: "Avoid hidden monsters: 0=no, 1=yes",

    // Caching
    cachePlayerNames: "Cache player names: 0=no, 1=yes",
    cachePlayerNames_duration: "How long to cache player names (seconds)",
    cachePlayerNames_maxSize: "Maximum cache size",

    // Client Settings
    clientSight: "Client's field of view radius",

    // Disconnect Settings
    dcPause: "Pause on disconnect: 0=no, 1=yes",
    dcOnDeath: "Disconnect when character dies: 0=no, 1=yes",
    dcOnDualLogin: "Disconnect on dual login: 0=no, 1=yes",
    dcOnDisconnect: "Disconnect on network disconnect: 0=no, 1=yes",
    dcOnEmptyArrow: "Disconnect when out of arrows: 0=no, 1=yes",
    dcOnMaxReconnections:
        "Disconnect after max reconnection attempts: 0=no, 1=yes",
    dcOnMute: "Disconnect if muted: 0=no, 1=yes",
    dcOnPM: "Disconnect on private message: 0=no, 1=yes",
    dcOnZeny: "Disconnect on low zeny: 0=no, 1=yes",
    dcOnStorageFull: "Disconnect when storage is full: 0=no, 1=yes",
    dcOnPlayer: "Disconnect when player found: 0=no, 1=yes",
    dcOnServerShutDown: "Disconnect on server shutdown: 0=no, 1=yes",
    dcOnServerClose: "Disconnect on server close: 0=no, 1=yes",
    dcOnJobLevel: "Disconnect at specific job level",
    dcOnLevel: "Disconnect at specific level",

    // Following
    follow: "Enable following another player: 0=no, 1=yes",
    followTarget: "Character name to follow",
    followEmotion: "Use emotion while following: 0=no, 1=yes",
    followEmotion_distance: "Distance to maintain for emotion",
    followFaceDirection: "Face direction of followed player: 0=no, 1=yes",
    followDistanceMax: "Maximum distance while following",
    followDistanceMin: "Minimum distance while following",
    followLostStep: "Steps to take when lost",
    followSitAuto: "Sit when followed player sits: 0=no, 1=yes",
    followBot: "Follow only bot characters: 0=no, 1=yes",

    // Item Management
    itemsTakeAuto:
        "Automatically pick up items: 0=off, 1=pick all, 2=whitelist",
    itemsTakeAuto_party: "Pick items party drops: 0=no, 1=yes",
    itemsGatherAuto: "Auto-gather items: 0=no, 1=yes",
    itemsGatherAuto_notInTown: "Don't gather in towns: 0=no, 1=yes",
    itemsGatherAutoMinPlayerDistance:
        "Min distance from other players to gather",
    itemsGatherAutoMinPortalDistance: "Min distance from portals to gather",
    itemsMaxWeight: "Maximum weight before stopping pickup (percentage)",
    itemsMaxWeight_sellOrStore: "Max weight before selling/storing",
    itemsMaxNum_sellOrStore: "Max item count before selling/storing",
    cartMaxWeight: "Max cart weight",
    itemsTakeGreed: "Take items with greed priority: 0=no, 1=yes",
    itemsCheckWeight: "Check weight before taking items: 0=no, 1=yes",

    // Map Locking
    lockMap: "Lock character to a specific map",
    lockMap_x: "X coordinate for map lock",
    lockMap_y: "Y coordinate for map lock",
    lockMap_randX: "Random X variance for lock",
    lockMap_randY: "Random Y variance for lock",

    // Routing
    route_escape_reachedNoPortal: "Escape when no portal found: 0=no, 1=yes",
    route_escape_randomWalk: "Random walk when escaping: 0=no, 1=yes",
    route_escape_shout: "Shout when escaping: 0=no, 1=yes",
    route_avoidWalls: "Avoid walls while routing: 0=no, 1=yes",
    route_randomWalk: "Enable random walk: 0=no, 1=yes",
    route_randomWalk_inTown: "Random walk in towns: 0=no, 1=yes",
    route_randomWalk_maxRouteTime: "Max route time for random walk",
    route_maxWarpFee: "Max fee for warping",
    route_maxNpcTries: "Max NPC interaction tries",
    route_teleport: "Use teleport for routing: 0=no, 1=yes",
    route_teleport_minDistance: "Min distance to use teleport",
    route_teleport_maxTries: "Max teleport tries",
    route_teleport_notInMaps: "Maps where teleport is disabled",
    route_step: "Steps per route cycle",
    route_removeMissingPortals_NPC: "Remove missing NPC portals: 0=no, 1=yes",
    route_removeMissingPortals: "Remove missing portals: 0=no, 1=yes",
    route_tryToGuessMissingPortalByDistance:
        "Try to guess missing portals: 0=no, 1=yes",
    route_reAddMissingPortals: "Re-add missing portals: 0=no, 1=yes",
    route_randomFactor: "Random factor for routing",
    maxWalkPathDistance: "Max walk path distance",

    // Running Away
    runFromTarget: "Run away from attackers: 0=no, 1=yes",
    runFromTarget_inAdvance: "Run before being attacked: 0=no, 1=yes",
    runFromTarget_dist: "Distance to maintain while running",
    runFromTarget_minStep: "Minimum steps when running",
    runFromTarget_maxPathDistance: "Max path distance when running",
    runFromTarget_noAttackMethodFallback: "Fallback when can't attack",
    runFromTarget_noAttackMethodFallback_attackMaxDist:
        "Max distance for fallback",
    runFromTarget_noAttackMethodFallback_minStep: "Min steps for fallback",

    // Savepoint
    saveMap: "Savepoint map",
    saveMap_x: "Savepoint X coordinate",
    saveMap_y: "Savepoint Y coordinate",
    saveMap_warpToBuyOrSell: "Warp to savepoint for buy/sell",
    saveMap_warpChatCommand: "Chat command to use for warping",
    memo1: "Memo slot 1 location",
    memo2: "Memo slot 2 location",
    memo3: "Memo slot 3 location",
    memo4: "Memo slot 4 location",

    // Shop Settings
    shopAuto_open: "Auto-open vend shop: 0=no, 1=yes",
    shop_random: "Random shop pricing: 0=no, 1=yes",
    shop_useSkill: "Use skill for shop: 0=no, 1=yes",
    buyerShopAuto_open: "Auto-open buyer shop: 0=no, 1=yes",
    buyerShop_random: "Random buyer shop pricing: 0=no, 1=yes",

    // Sitting
    sitAuto_hp_lower: "Sit when HP drops below this percentage",
    sitAuto_hp_upper: "Stand when HP recovers above this percentage",
    sitAuto_sp_lower: "Sit when SP drops below this percentage",
    sitAuto_sp_upper: "Stand when SP recovers above this percentage",
    sitAuto_follow: "Sit with followed player: 0=no, 1=yes",
    sitAuto_over_50: "Sit when more than 50% below max: 0=no, 1=yes",
    sitAuto_idle: "Sit when idle: 0=no, 1=yes",
    sitAuto_look: "Look direction while sitting",
    sitAuto_look_from_wall: "Look at wall while sitting: 0=no, 1=yes",
    sitTensionRelax: "Relax tension after sitting: 0=no, 1=yes",

    // Stats & Skills
    statsAddAuto: "Automatically add stat points: 0=no, 1=yes",
    statsAddAuto_list: "Stats to add automatically",
    statsAddAuto_dontUseBonus: "Don't use bonus points: 0=no, 1=yes",
    statsAdd_over_99: "Add stats even if over 99: 0=no, 1=yes",
    skillsAddAuto: "Automatically add skill points: 0=no, 1=yes",
    skillsAddAuto_list: "Skills to add automatically",

    // Tank Mode
    tankMode: "Enable tank mode (protect others): 0=no, 1=yes",
    tankModeTarget: "Target to tank for",

    // Teleport
    teleportAuto_hp: "Teleport when HP drops below this percentage",
    teleportAuto_sp: "Teleport when SP drops below this percentage",
    teleportAuto_idle: "Teleport when idle: 0=no, 1=yes",
    teleportAuto_portal: "Teleport to portal: 0=no, 1=yes",
    teleportAuto_search: "Teleport to search for enemies: 0=no, 1=yes",
    teleportAuto_minAggressives: "Min aggressive monsters before teleport",
    teleportAuto_minAggressivesInLock: "Min aggressives in locked map",
    teleportAuto_onlyWhenSafe: "Only teleport when safe: 0=no, 1=yes",
    teleportAuto_maxDmg: "Max damage before teleport",
    teleportAuto_maxDmgInLock: "Max damage in locked map",
    teleportAuto_deadly: "Enable teleport to escape death: 0=no, 1=yes",
    teleportAuto_useSkill: "Use skill for teleport: 0=no, 1=yes",
    teleportAuto_useChatCommand: "Chat command for teleport",
    teleportAuto_allPlayers: "Teleport from all players: 0=no, 1=yes",
    teleportAuto_notPlayers: "Players to exclude from teleport",
    teleportAuto_atkCount: "Attack count before teleport",
    teleportAuto_atkMiss: "Miss count before teleport",
    teleportAuto_unstuck: "Teleport to get unstuck: 0=no, 1=yes",
    teleportAuto_lostTarget: "Teleport when lost target: 0=no, 1=yes",
    teleportAuto_dropTarget: "Teleport to drop target: 0=no, 1=yes",
    teleportAuto_dropTargetKS: "Teleport to avoid KS: 0=no, 1=yes",
    teleportAuto_dropTargetHidden: "Teleport from hidden targets: 0=no, 1=yes",
    teleportAuto_attackedWhenSitting:
        "Teleport when attacked while sitting: 0=no, 1=yes",
    teleportAuto_totalDmg: "Total damage before teleport",
    teleportAuto_totalDmgInLock: "Total damage in locked map",
    teleportAuto_equip_leftAccessory: "Accessory for teleport",
    teleportAuto_equip_rightAccessory: "Right accessory for teleport",
    teleportAuto_lostHomunculus: "Teleport if homunculus lost: 0=no, 1=yes",
    teleportAuto_useItemForRespawn:
        "Use item for respawn after teleport: 0=no, 1=yes",
    teleportAuto_item1: "Item 1 for teleport respawn",
    teleportAuto_item2: "Item 2 for teleport respawn",

    // Trading & Party
    dealAuto: "Automatically accept trade requests: 0=no, 1=yes",
    dealAuto_names: "Player names for auto-trade",
    partyAuto: "Automatically accept party invitations: 0=no, 1=yes",
    partyAutoShare: "Share party items automatically: 0=no, 1=yes",
    partyAutoShareItem: "Share items in party: 0=no, 1=yes",
    partyAutoShareItemDiv: "Share items division method",
    guildAutoDeny: "Automatically deny guild invitations: 0=no, 1=yes",
    attendanceAuto: "Auto-attend guild attendance: 0=no, 1=yes",

    // Logging & Display
    verbose: "Verbose logging level",
    showDomain: "Show message domains: 0=no, 1=yes",
    showDomain_NPC: "Show NPC domain messages: 0=no, 1=yes",
    showDomain_Shop: "Show shop domain messages: 0=no, 1=yes",
    squelchDomains: "Domains to silence",
    verboseDomains: "Domains for verbose logging",
    beepDomains: "Domains to beep on",
    beepDomains_notInTown: "Don't beep in towns: 0=no, 1=yes",
    friendlyAID: "Friendly player IDs",
    showTime: "Show timestamps: 0=no, 1=yes",
    showTimeDomains: "Domains to show timestamps for",
    showTimeDomainsFormat: "Timestamp format",
    wx_map_maxAutoSize: "Max auto-size for map",
    wx_map_monsterSticking: "Sticky monsters on map: 0=no, 1=yes",
    wx_map_npcSticking: "Sticky NPCs on map: 0=no, 1=yes",
    wx_map_playersSticking: "Sticky players on map: 0=no, 1=yes",
    wx_map_portalSticking: "Sticky portals on map: 0=no, 1=yes",
    wx_map_route: "Show route on map: 0=no, 1=yes",
    wx_npcTalk: "Show NPC talk on map: 0=no, 1=yes",
    wx_captcha: "Show captcha on map: 0=no, 1=yes",
    showAllDamage: "Show all damage: 0=no, 1=yes",
    manualURL: "URL to manual",
    forumURL: "URL to forum",

    // Log Files
    logChat: "Log chat messages: 0=no, 1=yes",
    logPrivateChat: "Log private messages: 0=no, 1=yes",
    logPartyChat: "Log party chat: 0=no, 1=yes",
    logGuildChat: "Log guild chat: 0=no, 1=yes",
    logSystemChat: "Log system messages: 0=no, 1=yes",
    logLocalBroadcast: "Log local broadcasts: 0=no, 1=yes",
    logShop: "Log shop information: 0=no, 1=yes",
    logEmoticons: "Log emoticons: 0=no, 1=yes",
    logConsole: "Log to console: 0=no, 1=yes",
    logAppendUsername: "Append username to logs: 0=no, 1=yes",
    logAppendServer: "Append server to logs: 0=no, 1=yes",
    monsterLog: "Log monster encounters: 0=no, 1=yes",
    playerLog: "Log player encounters: 0=no, 1=yes",
    logDead: "Log deaths: 0=no, 1=yes",

    // Display Settings
    questDisplayStyle: "Quest display style",
    chatTitleOversize: "Chat title size",
    shopTitleOversize: "Shop title size",
    buyerShopTitleOversize: "Buyer shop title size",
    sleepTime: "Sleep time in milliseconds",

    // Miscellaneous
    ignoreAll: "Ignore all messages: 0=no, 1=yes",
    itemHistory: "Keep item history: 0=no, 1=yes",
    autoTalkCont: "Auto-continue NPC talk: 0=no, 1=yes",
    noAutoSkill: "Disable auto-skill: 0=no, 1=yes",
    portalCompile: "Compile portals: 0=no, 1=yes",
    portalRecord: "Record portal usage: 0=no, 1=yes",
    portalRecord_recompileAfter: "Recompile portals after use: 0=no, 1=yes",
    missDamage: "Count missed attacks as damage: 0=no, 1=yes",
    tankersList: "List of tanks",
    repairAuto: "Auto-repair equipment: 0=no, 1=yes",
    repairAuto_list: "Equipment to auto-repair",
    status_mapProperty: "Show map property status: 0=no, 1=yes",
    status_mapType: "Show map type status: 0=no, 1=yes",
    monster_filter: "Monster filter pattern",

    // Mercenary Settings
    mercenary_attackAuto:
        "Mercenary attack mode: 0=off, 1=attack, 2=attack+skill",
    mercenary_attackAuto_party: "Mercenary attack party enemies: 0=no, 1=yes",
    mercenary_attackAuto_notInTown:
        "Mercenary don't attack in town: 0=no, 1=yes",
    mercenary_attackDistance: "Mercenary attack distance",
    mercenary_attackMaxDistance: "Mercenary max attack distance",
    mercenary_teleportAuto_hp: "Mercenary teleport HP threshold",
    mercenary_teleportAuto_deadly: "Mercenary escape death: 0=no, 1=yes",
    mercenary_tankMode: "Mercenary tank mode: 0=no, 1=yes",

    // Homunculus Settings
    homunculus_attackAuto:
        "Homunculus attack mode: 0=off, 1=attack, 2=attack+skill",
    homunculus_attackAuto_party: "Homunculus attack party enemies: 0=no, 1=yes",
    homunculus_attackDistance: "Homunculus attack distance",
    homunculus_attackMaxDistance: "Homunculus max attack distance",
    homunculus_teleportAuto_hp: "Homunculus teleport HP threshold",
    homunculus_autoFeed: "Auto-feed homunculus: 0=no, 1=yes",
    homunculus_hunger: "Homunculus hunger threshold",
    homunculus_return: "Homunculus return hunger threshold",
    homunculus_autoFeedAllowedMaps: "Maps where homunculus is fed",

    // Pet Settings
    pet_autoFeed: "Auto-feed pet: 0=no, 1=yes",
    pet_hunger: "Pet hunger threshold",
    pet_return: "Pet return hunger threshold",

    // Blocks
    attackSkillSlot: "Configuration for attack skills",
    attackComboSlot: "Configuration for attack combos",
    doCommand: "Configuration for commands",
    useSelf_skill: "Configuration for self-cast skills",
    useSelf_skill_smartHeal: "Smart healing threshold",
    partySkillDistance: "Party skill range",
    partySkill: "Configuration for party skills",
    monsterSkill: "Configuration for monster skills",
    autoSwitch_default_rightHand: "Default right-hand weapon",
    autoSwitch_default_leftHand: "Default left-hand weapon",
    autoSwitch_default_arrow: "Default arrow",
    autoSwitch: "Weapon switch configuration",
    equipAuto: "Auto-equip configuration",
    useSelf_item: "Configuration for item use",
    buyAuto: "Auto-buy configuration",
    sellAuto: "Auto-sell enabled: 0=no, 1=yes",
    sellAuto_npc: "NPC for selling",
    sellAuto_standpoint: "Standpoint for selling",
    sellAuto_distance: "Distance for selling",
    storageAuto: "Auto-storage enabled: 0=no, 1=yes",
    storageAuto_npc: "NPC for storage",
    storageAuto_standpoint: "Standpoint for storage",
    storageAuto_distance: "Distance for storage",
    storageAuto_npc_type: "Storage NPC type",
    storageAuto_type: "Storage type",
    storageAuto_keepOpen: "Keep storage open: 0=no, 1=yes",
    storageAuto_useChatCommand: "Use chat command for storage: 0=no, 1=yes",
    storageAuto_useItem: "Use item for storage: 0=no, 1=yes",
    relogAfterStorage: "Relog after storage: 0=no, 1=yes",
    minStorageZeny: "Minimum zeny to keep",
    npcTimeResponse: "NPC response time",
    getAuto: "Auto-get configuration",

    // Debugging
    debug: "Enable debugging: 0=no, 1=yes",
    debugPacket_unparsed: "Debug unparsed packets: 0=no, 1=yes",
    debugPacket_received: "Debug received packets: 0=no, 1=yes",
    debugPacket_ro_sent: "Debug RO sent packets: 0=no, 1=yes",
    debugPacket_sent: "Debug sent packets: 0=no, 1=yes",
    debugPacket_exclude: "Exclude patterns from debug",
    debugPacket_include: "Include patterns in debug",
    debugDomains: "Debug specific domains",
    logToFile_Debug: "Log debug to file: 0=no, 1=yes",
    logToFile_Errors: "Log errors to file: 0=no, 1=yes",
    logToFile_Messages: "Log messages to file: 0=no, 1=yes",
    logToFile_Warnings: "Log warnings to file: 0=no, 1=yes",
    history_max: "Maximum command history size",
};
